# Generated by Django 5.0.2 on 2026-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_membershipplancontent_basic_plan_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProductsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Featured Products', help_text='Title shown above the featured products section', max_length=200)),
                ('section_description', models.TextField(default='Hand-picked programs and equipment from our store', help_text='Description text shown below the title in the featured products section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured Products Content',
                'verbose_name_plural': 'Featured Products Content',
            },
        ),
    ]
