"""
Django settings for fitness_club project.
Generated by 'django-admin startproject' using Django 5.0.2.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")  # loads your .env from project root



# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
# Your project is nested like: root/fitness_club/fitness_club/settings.py
# so parent.parent.parent points to the repo root (where /templates, /static live)
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ------------------------------------------------------------
# Core settings
# ------------------------------------------------------------
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-change-me")
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# ALLOWED_HOSTS from environment variable (comma-separated)
# Example: ALLOWED_HOSTS=ec2-15-223-56-68.ca-central-1.compute.amazonaws.com,example.com
allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "")
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]
else:
    # Default for local development
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# CSRF_TRUSTED_ORIGINS from environment variable (comma-separated)
# Example: CSRF_TRUSTED_ORIGINS=https://ec2-15-223-56-68.ca-central-1.compute.amazonaws.com,https://example.com
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(",") if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

# Replit support (safe locally)
replit_domains = os.environ.get("REPLIT_DOMAINS")
if replit_domains:
    domain_list = [d.strip() for d in replit_domains.split(",") if d.strip()]
    ALLOWED_HOSTS += domain_list
    CSRF_TRUSTED_ORIGINS += [f"https://{d}" for d in domain_list]

# ------------------------------------------------------------
# Applications
# ------------------------------------------------------------
INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Third-party
    "rest_framework",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    # your apps
    "home",
    "products",
    "cart",
    "orders",
    "payment",
    "members",
    "accounts",
    "core",
    "profiles.apps.ProfilesConfig",

]

# ------------------------------------------------------------
# Middleware
# ------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # required for django-allauth
    "allauth.account.middleware.AccountMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ------------------------------------------------------------
# URLs / WSGI / ASGI
# ------------------------------------------------------------
ROOT_URLCONF = "fitness_club.fitness_club.urls"
WSGI_APPLICATION = "fitness_club.fitness_club.wsgi.application"
ASGI_APPLICATION = "fitness_club.fitness_club.asgi.application"

# ------------------------------------------------------------
# Templates
# ------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",  # required for allauth
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ------------------------------------------------------------
# Database
# ------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "fitness_club_db"),
        "USER": os.environ.get("POSTGRES_USER", "fitness_user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# ------------------------------------------------------------
# Auth / Allauth
# ------------------------------------------------------------
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Modern allauth settings (Django 5+)
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Use email for authentication
ACCOUNT_EMAIL_REQUIRED = True  # Required when using email authentication
ACCOUNT_UNIQUE_EMAIL = True  # Required when login isn't username-only
ACCOUNT_USERNAME_REQUIRED = False  # Username not required when using email
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

# Redirects
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# ------------------------------------------------------------
# Email
# ------------------------------------------------------------
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Fitness Club <no-reply@lwsoc.com>"
)

# Always enforce verification rules (recommended)
ACCOUNT_EMAIL_VERIFICATION = os.environ.get("ACCOUNT_EMAIL_VERIFICATION", "mandatory")
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Choose backend based on DEBUG or EMAIL_BACKEND env var
# Allow overriding email backend via environment variable for testing
email_backend_override = os.environ.get("EMAIL_BACKEND", "")
if email_backend_override:
    EMAIL_BACKEND = email_backend_override
elif DEBUG:
    # Dev: print emails to console (you'll see the verification link in logs)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

    EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() == "true"
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_TIMEOUT = 10  # Timeout in seconds for SMTP connection

    if EMAIL_USE_TLS and EMAIL_USE_SSL:
        raise ValueError("Only one of EMAIL_USE_TLS or EMAIL_USE_SSL can be True.")



# ------------------------------------------------------------
# Password validation
# ------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------
# Static / Media
# ------------------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # For production (collectstatic)

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ------------------------------------------------------------
# Defaults
# ------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
