# Generated by Django 5.0.2 on 2025-12-21 06:23

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_digitaldownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldownload',
            name='expires_at',
            field=models.DateTimeField(default=orders.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='digitaldownload',
            name='max_downloads',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='digitaldownload',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
