# Generated by Django 5.0.2 on 2025-12-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_productaudio_is_digital_productaudio_is_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaudio',
            name='is_digital',
        ),
        migrations.RemoveField(
            model_name='productaudio',
            name='is_service',
        ),
        migrations.RemoveField(
            model_name='productaudio',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='productaudio',
            name='service_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='productaudio',
            name='service_location',
        ),
        migrations.RemoveField(
            model_name='productaudio',
            name='service_time',
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='service_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Length of class in minutes', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='service_location',
            field=models.CharField(blank=True, help_text='e.g. Studio Room A, Zoom link, park location', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='service_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
