# Generated by Django 5.0.2 on 2025-12-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_productaudio_is_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Number of seats. Leave blank for unlimited.', null=True),
        ),
    ]
