# Generated by Django 5.0.2 on 2025-12-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, choices=[('canadapost', 'Canada Post'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('dhl', 'DHL'), ('other', 'Other / Local')], help_text='Shipping company for physical items', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number (if applicable)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
