# Generated by Django 5.0.2 on 2025-12-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_order_shipping_carrier_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='If enabled, membership will auto-renew each month (logic only, no real billing).'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='last_billed_date',
            field=models.DateField(blank=True, help_text="Most recent date membership was 'renewed'.", null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='membership_level',
            field=models.CharField(choices=[('none', 'No membership'), ('basic', 'Facility only – unlimited gym access'), ('premium', 'Facility + unlimited in-class training')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='next_billing_date',
            field=models.DateField(blank=True, help_text='Date of next renewal charge (for display / logic only).', null=True),
        ),
    ]
