# Generated by Django 5.0.2 on 2025-12-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_memberprofile_address1_memberprofile_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='digital_products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
