# Generated by Django 5.0.2 on 2025-12-22 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_product_digital_file_product_digital_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productaudio',
            name='product',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='province',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='last_billed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ProductVideo',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAudio',
        ),
    ]
