# Generated by Django 5.0.2 on 2026-01-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_membershipplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(help_text='Brief description. HTML supported: &lt;p&gt;, &lt;ul&gt;, &lt;li&gt;, &lt;strong&gt;, etc.'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Additional details (optional). HTML supported: &lt;ul&gt;&lt;li&gt; for lists, &lt;p&gt; for paragraphs.'),
        ),
    ]
